### ISSUE TITLE
Send text without selection?

### ISSUE THREAD

**Issue by Spirarel** [normen/vim-macos-scripts#1]
Hey nice job on these, they are very convenient.

I'm not an shortcut/applescript hero—do you know is there a way to eliminate the select-all step before invoking the shortcut and just send all the text in the current input box? That would be... well, one keystroke fewer.

**Comment by normen** [comment]
No, thats the actual function of MacOS thats being used here, replacing selected text. Thats why it works in all apps.

**Comment by Spirarel** [comment]
Bummer. Well thanks for responding.

**Comment by normen** [comment]
I mean you can just use the open action then, right?

**Comment by Spirarel** [comment]
I don't think so? Let's say I'm authoring some message (like in this github box).
In the currently script, I can't just trigger the quick action and edit in vim. I have to select all the text first, then trigger the action. This is really quite minor, but again it's an additional keypress.

I did look more into shortcuts, but it looks like both text and `.txt` files have the same Shortcut's "type", so branching high up didn't seem viable. I wouldn't be surprised if there was a way to do this in Applescript.

**Comment by normen** [comment]
No, but then again in this case (this text box) you'd press the shortcut before typing any text. I was thinking about opening a whole file.

You could use hammerspoon or something to automate the keypress, maybe you can somehow shove it into the current script. What I'd say makes more sense is making the shortcut adjacent to the select all shortcut, like `Cmd-a` - `Cmd-Ctrl-Option-a`. Having the option to not select all text is imo preferable, especially as you can't tell beforehand which app reacts how when you press "select all".
